### ISSUE TITLE
Support Nanosecond Display

### ISSUE THREAD

**Issue by abigalesong** [arkime/arkime#1454]
**Elasticsearch version**:

**Moloch version**:

**OS name and version**:

**How was Moloch built/installed:** (rpm, deb, easybutton, ...)

**Provide logs, stack traces and steps to reproduce**:

**Comment by awick** [comment]
Currently Moloch uses milliseconds for all dates because that is what ES 6 and before supports. Once we stop supporting ES 6, we can use the ES 7 nanosecond date field type.

Since pcap files only support up to microseconds we will not be able to have full nanosecond support until we switch to pcapng

**Comment by WGH-** [comment]
> Since pcap files only support up to microseconds we will not be able to have full nanosecond support until we switch to pcapng

I'm pretty sure plain pcaps have nanosecond support. They have 0xa1b23c4d magic instead of usual 0xa1b2c3d4. `tcpdump` can write them with `--time-stamp-precision nanosecond` switch.

**Comment by awick** [comment]
Good point, still doesn't change the answer.
