### ISSUE TITLE
Сhanges /upload and /api/upload

### ISSUE THREAD

**Issue by salenaf** [arkime/arkime#1753]
**Changing the functions of those responsible for '/upload' and '/api/upload'** 

Using this code, we managed to fix the '/upload' page: it uploads the .pcap file to the '/tmp' folder, then transfers it to '/arkime/raw', keeping the original name, and deletes the file from the '/tmp' folder. 

Elasticsearch version end Arkime/Moloch version: last
OS name and version: linux

**file 'arkime/viewer/viewer.js'   [line 1921]** 
// uploads apis ---------------------------------------------------------------
```
const storage = multer.diskStorage({
    destinatiom: (req, file, cb) => {
        cb(null, '/tmp');
    },
    filename: (req, file, cb) => {
        cb(null, file.originalname);         //save original name pcap file
    }
});
const upload = multer({ storage: storage });

app.post(
    ['/api/upload', '/upload'],
    //  [checkCookieToken, multer({ dest: '/tmp', limits: internals.uploadLimits }).single('file')],
    [checkCookieToken, upload.single('file')],
    miscAPIs.upload
);
```

**file 'arkime/etc/config.ini'  [linе 238]**
_because **the '--copy' function does not work as expected** (it split the test file into 2 separate files), I had to use additional functions to move the file to the '/arkime/raw/' folder_ 
`uploadCommand = (/usr/sbin/tcpdump -w /opt/arkime/raw/{ FILENAME } -r { TMPFILE }) && /opt/arkime/bin/capture -r /opt/arkime/raw/{ FILESAVE } -c { CONFIG } { TAGS } && rm { TMPFILEDEL }`

**file 'arkime/viewer/apiMisc.js'  changing the parameters of the function 'Config.get('uploadCommand')'  [line 201]**
// upload apis --------------------------------------------------------------

```
let fileName = req.file.filename;
const cmd = Config.get('uploadCommand')
        .replace('{TAGS}', tags)
        .replace('{CONFIG}', Config.getConfigFile())
        //.replace('{NODE}', Config.nodeName())
        .replace('{FILENAME}', fileName)                                   // opt/arkime/raw
        .replace('{FILESAVE}', fileName)                                     // file name to save to arkime
        .replace('{TMPFILE}', req.file.path)                                 // /tmp
        .replace('{TMPFILEDEL}', req.file.path);                          // remove file in fload /tmp
```

**Comment by awick** [comment]
* This would be better as a PR instead of a github issue
* In general it is considered a large security issue to use the filename provided, especially if it isn't scrubbed or checked if that file already exists
* Why does it matter if it is split into multiple files? If it really does matter just increase the max file size in Arkime
* The upload command in general is just a toy, if you really have files so big that they are getting split, you should just be copying them to the machine and running arkime capture yourself.
* Unclear why you commented out the NODE replacement?
* What is the purpose of TEMPFILEDEL vs TMPFILE and FILESAVE vs FILENAME?
* If you really wanted to copy the file you should use the "cp" command instead of "tcpdump"
