### ISSUE TITLE
Unsanitized input from the HTTP request body [:313] flows [:313, :313, :311] into send [:311], where it is used to render an HTML page returned to the user. This may result in a Cross-Site Scripting attack (XSS).

### ISSUE THREAD

**Issue by gustiaryaaaa** [arkime/arkime#2047]
https://github.com/arkime/arkime/blob/2c2dcaa0a1a511acf6d6226462a418d095d895bc/common/notifier.js#L311

**Comment by awick** [comment]
Sorry I thought I replied earlier, could you review https://arkime.com/security and if you think it is still an issue submit thru H1? (You might even get some money.) I'm not really sure since its a POST and you have to be an admin how it could be used for badness, but would love to learn.

We've been working a bunch lately on input sanitization so we might have already fixed this one, and there are a few out of scope issues listed on the page.
