### ISSUE TITLE
periodic query schedule control

### ISSUE THREAD

**Issue by Obsecurus** [arkime/arkime#2081]
The periodic query functionality only supports the fixed 90 second interval currently. It would be awesome if you could specify the cron pattern on these.   For example if you have a handful of queries you wish to run on a regular interval it would be nice to tune the frequency so you can balance performance concerns for things that might be looking over very large time windows.

**Comment by awick** [comment]
So currently the cron thread checks every 60 seconds if something needs to run, and then for each job that needs to run it will query up to a days worth of data before moving to the next job. Once all the jobs have all run once, it will requery all the waiting jobs and start again if there are any that haven't finished. 

The 90 seconds thing is just how fresh the data to look at should be, not how often it runs.

Two things:
* In the future please make the title short and not the whole feature request
* Can you maybe describe the issue you are having, instead of a potential solution, since by knowing the issue we might come up with a better solution, or we might use the one you provided. Without knowing the actual issue, we might solve for the wrong thing.

**Comment by Obsecurus** [comment]
This was not driven by a problem with the current architecture. The thinking was if you had a complex query that impacted ElasticSearch/OpenSearch performance that you only wish to run once a day at a specific time. The same would apply for a day of the week, but that appears not to apply given it's limited to "up to a days worth of data". I guess this could just be applied ad-hoc or via the APIs in that case.

 It seems periodic query is primarily designed for keeping up with the active flow of session information, this request likely stems from my misunderstanding of the feature, and maybe this ticket should close since it's not well-scoped.

**Comment by awick** [comment]
I'm first to admit the periodic query flow isn't the most friendly/clear and could probably use an overhaul. The goal is just to keep up with the data, and we don't have the concept of once a day or when you aren't busy type of queries. A priority  or once a X choice might be useful. 

However I'm reluctant to add full cron style control though, since large daily/weekly queries may actually be worse then smaller periodic runnings for system health. Recent data is more likely to be in all the caches or hot storage.
