### ISSUE TITLE
Launch Indicator Search

### ISSUE THREAD

**Issue by 31453** [arkime/arkime#2134]
Append a Link or Button at the top of each card display that launches a new browser tab to the 3rd party app search page for the indicator in question. This probably requires a new field in the integrations section in order to define the INTEGRATION_SEARCH_URL.

Where the title of each card becomes `${INTEGRATION} for ${indicator} `. link/button to `${INTEGRATION_SEARCH_URL}`

**Comment by 31453** [comment]
@WilliamSalusky was this your request?

How is this different than links? Maybe we could add a default link group that includes these? I feel like this functionality to very close to links and makes more sense there.

Also, there is a problem with certain resource's search capability. For example, Arkime, we need to know the iType of the indicator in order to create the link. If it's an ip, the query would be something like, `arkimeservice.org/sessions?expression=ip==10.0.0.1`. If it's domain, the query would be something like `arkimeservice.org/sessions?expression=hostname==test.com`. But if it were a phone number, it wouldn't apply. Also, services like censys don't have a single search endpoint, you need to know whether you're searching for a host or a certificate. So, again, we need to know the iType of the indicator.

Cards are generic and don't assume a specific iType, so I feel like this functionality makes more sense in a link group. Thoughts?

@awick what do you think?

**Comment by WilliamSalusky** [comment]
The intent is to make it as simple as possible to get from a specific card view to the full third party UI web app and not have to navigate the link group section since we are already looking at the card. (card displays are pretty stripped down result sets as compared to what the integration specific full UI external app would display). Virustotal and URLScan are good examples. In most cases the card display is good enough, but in plenty of cases I do want to see all of the additional data enrichment that the full web app presents and is unique to the full app, also not accessible via API results.
