### ISSUE TITLE
Create the structures and data needed to use the S3 bucket for Yum repositories

### ISSUE THREAD

**Issue by N0K0** [arkime/arkime#2223]
**Is your feature request related to a problem? Please describe.**
I would like to manage Arkime via yum, to do this I need an index

**Describe the solution you'd like**
From reading over this: 

https://reece.tech/posts/hosting-centos-7-and-8-yum-repositories-in-s3
https://github.com/stefanfreitag/s3_yum_repository

With help of the `createrepo` tool, it should be possible to create what is needed for your S3 bucket to work as a repo for yum.

**Describe alternatives you've considered**
Downloading all artifacts locally and setting up my own index locally. Which is a pain compared to mirroring something already setup by the source

**Comment by awick** [comment]
Thanks for opening an issue and links. Can you explain why you need this and why it is better than just `yum install <url>`.

I'm not sure we will spend time on this, so it would probably require someone to contribute the PR, and it should support both rpm and deb solutions. We are also thinking of moving to github releases, so not sure how that plays into this.

**Comment by awick** [comment]
The downloads page has a list of all versions. Auto updates are a little scary and I wouldn't recommend. We can leave the issue open for a while and see if anyone wants to implement, but not something we are going to do at this time.

**Comment by awick** [comment]
>  It would be even cooler with a well-known format supported out of the box from the OS :D

What does that mean? We already use a well known formats, rpm, zst and deb.

The only change this will get you is you can type
`yum install arkime` instead of `yum install https://s3.amazonaws.com/files.molo.ch/builds/centos-8/arkime-4.2.0-1.x86_64.rpm`

yes it is shorter, but in the https version I know exactly what I'm getting. Plus I use an orchestration system to do it, so it's even easier.

There is nothing more annoying than getting a new repo on a whole bunch of boxes and making sure you get the new gpg key installed or updated. I'm assuming you want to sign everything in this new repo.

Anyway, you'll need to look at the screwdriver file and make a new job kind of the slack one that only runs once.
