### ISSUE TITLE
specifying freeSpaceG as gigabytes not working

### ISSUE THREAD

**Issue by mmguero** [arkime/arkime#2886]
[freeSpaceG](https://arkime.com/settings#freespaceg)'s documentation states:

> Delete pcap files when free space is lower then this. This does NOT delete the session records in the database. It is recommended this value is between 5% and 10% of the disk. Database deletes are done by the db.pl expire. Can also be specified using a percentage. 

implying that if it's *not* specified as a percentage, the number represents a fixed gigabytes value.

A user wanted to set the behavior to "delete PCAP files when free space is lower than 100 gigabytes" so they just set that value at `100`. He reported that the disk filled up with PCAP.

**Comment by awick** [comment]
works for me. :) I did make some changes in #2887 that might make it easier to figure out whats going on. Setting to 100 will NOT work with the default settings since we keep 10 files around which will require 120G. Also improved https://arkime.com/faq#pcap-deletion and https://arkime.com/settings#maxFileSizeG
