### ISSUE TITLE
Removing sudo from easybutton_build.sh

### ISSUE THREAD

**Issue by D3vil0p3r** [arkime/arkime#2951]
I'm using `easybutton_build.sh` to create an Arch Linux package. In this kind of environment, the usage of sudo is meaningless.

To manage this kind of case, could you please remove "sudo" commands from the launched commands in the script, or enable it only if a `--run-as-root` argument is provided please?

**Comment by awick** [comment]
Is there a reason you don't want to use the arch package we already build?
Since easybutton-build.sh isn't required to build arkime, you can just use configure directly, not sure this change is needed

**Comment by D3vil0p3r** [comment]
@awick The reason is that we use a dedicated repository to maintain all the pentesting tools. Probably the easiest way for us could be if you can provide the related PKGBUILD file you use to generate that arch package please.

**Comment by awick** [comment]
Could you download our pkg and reupload to your repo?

If you want to build yourself you can find the fpm command in .github/workflows/release.yml

**Comment by awick** [comment]
easybutton-build.sh doesn't have to be removed, that is your choice.

To build arkime it would be like any other auto tools project:
```./bootstrap.sh
./configure```

You can see what options we use with configure for arch by looking at easybutton-build.sh but you can use different options.

As far as packaging since we using fpm I have no clue what a PKGBUILD would look like.
