### ISSUE TITLE
Can't filter by hunt id or name

### ISSUE THREAD

**Issue by divinehawk** [arkime/arkime#2955]
**Describe the bug**
Creating a hunt and then searching by either huntId or huntName fails. Manually search filter to lowercase works.

**Elasticsearch version**: Opensearch 2.16.0

**Arkime/Moloch version**: 5.2.0

**OS name and version**: Amazon Linux 2

**How was Arkime/Moloch built/installed:** Docker

**Provide logs, stack traces and steps to reproduce**:
1: Create hunt, click Open Results in Session Tab.
Filter appears as : `huntId == tGedc5IBImtPIg2FLy1G`
With no results

2: Change filter to lowercase: `huntId == tgedc5ibimtpig2fly1g`
Results appear

There is similar behavior with hunt name

Arkime debug log shows filter as:
{
 "term" : {
   "huntId": "tGedc5IBImtPIg2FLy1G"
 }

Should this be huntId.keyword ?

**Comment by awick** [comment]
No, we don't use .keyword most places. Sounds like your mappings are messed up or have a template that is overriding defaults for string fields.

Could you come over to slack, would be easier to discuss?

Otherwise do a `curl http://localhost:9200/[arkime_sessions_index]/_mapping?pretty` and make sure huntId is a keyword.

**Comment by divinehawk** [comment]
This was related to a template being applied by Malcolm. https://github.com/idaholab/Malcolm/issues/554

Thanks for the nudge!
